language: node_js
node_js:
  - "6"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - psql --host=localhost -c 'CREATE DATABASE clicker;' -U postgres
env:
  - DB_HOST='localhost' DB_USERNAME='postgres' DB_PASSWORD='' DB_NAME='clicker'
