language: node_js
node_js:
  - "6"
services:
  - postgresql
before_install:
  - psql -c 'create database clicker;' -U postgres
env:
  - DB_HOST='127.0.0.1' DB_USERNAME='postgres' DB_PASSWORD='' DB_NAME='clicker'
